// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Venus Contributors

// AUTO-GENERATED by scripts/generate-endpoint-hosts.ts — DO NOT EDIT.
// Source: https://models.dev/api.json (hostnames only; request-body parameter
// shapes remain hand-written in reasoning.ts). Regenerate with:
//   bun run generate:endpoints

import type { EndpointBehavior } from './reasoning.js';

/**
 * Host substring → endpoint behavior lookup table used by `detectEndpointBehavior`.
 * Order matters — first match wins: manual entries, then models.dev-derived
 * hostnames (longest first), then broad domain fallbacks.
 */
export const ENDPOINT_HOSTS: ReadonlyArray<readonly [string, EndpointBehavior]> = [
  // Manual entries (missing from models.dev or served via native SDKs there)
  ['qianfan.baidubce.com', 'qianfan'],
  ['ark.cn-beijing.volces.com', 'volcanoark'],
  ['generativelanguage.googleapis.com', 'gemini'],
  ['api.x.ai', 'grok'],
  // Derived from models.dev api.json
  ['token-plan.ap-southeast-1.maas.aliyuncs.com', 'dashscope'],
  ['token-plan.cn-beijing.maas.aliyuncs.com', 'dashscope'],
  ['coding-intl.dashscope.aliyuncs.com', 'dashscope'],
  ['coding.dashscope.aliyuncs.com', 'dashscope'],
  ['token-plan-ams.xiaomimimo.com', 'mimo'],
  ['token-plan-sgp.xiaomimimo.com', 'mimo'],
  ['token-plan-cn.xiaomimimo.com', 'mimo'],
  ['dashscope-intl.aliyuncs.com', 'dashscope'],
  ['dashscope.aliyuncs.com', 'dashscope'],
  ['api.xiaomimimo.com', 'mimo'],
  ['api.deepseek.com', 'deepseek'],
  ['api.minimaxi.com', 'minimax'],
  ['open.bigmodel.cn', 'zhipu'],
  ['api.moonshot.ai', 'kimi'],
  ['api.moonshot.cn', 'kimi'],
  ['api.stepfun.com', 'stepfun'],
  ['api.minimax.io', 'minimax'],
  ['api.stepfun.ai', 'stepfun'],
  ['openrouter.ai', 'openrouter'],
  ['api.kimi.com', 'kimi'],
  // Broad domain fallbacks
  ['deepseek.com', 'deepseek'],
  ['moonshot.cn', 'kimi'],
  ['moonshot.ai', 'kimi'],
  ['xiaomimimo.com', 'mimo'],
  ['bigmodel.cn', 'zhipu'],
  ['minimaxi.com', 'minimax'],
  ['minimax.io', 'minimax'],
  ['stepfun.com', 'stepfun'],
  ['stepfun.ai', 'stepfun'],
];
